### ISSUE TITLE
지도에 사용할 마커 클래스 데이터 변경

### ISSUE THREAD

**Issue by choius323** [SSAFY-TOTT/Android#5]
# 개요

- 지도에서 사용하는 클러스터링 마커 클래스 데이터 변경

## 할 일

건물 데이터
- latitude, longtitude
- 자치구, 법정동명
- 건물명

매물 데이터
- 층, 평수, 전셋값
- 매물 ID

한 건물에 여러 개의 매물이 들어감

**Comment by KIMSEI1124** [comment]
# 데이터 변수명

전세값 : price
지역구 : districtName
법정동 : legalDongName
건물명 : buildingName
층 : floor
평수 : area
